In [127]:
import pandas as pd
import numpy as np
import random
import os

# read csv

In [128]:
os.listdir()

['KFC Project.ipynb',
 '.config',
 '.ipython',
 'Inbox',
 'KFC Project 2.ipynb',
 'Pandas-Data-Science-Tasks-master',
 'KFC-table.csv',
 '.ipynb_checkpoints',
 '.jupyter',
 'KFC Project.html',
 '.Trash',
 'fig2_bwdscat2.csv',
 'Sales-April.csv',
 'KFC-micro.csv']

In [129]:
df=pd.read_csv('KFC-table.csv',index_col='Timestamp')
df.shape

(32, 29)

In [130]:
df.tail(2)

ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Original ( thigh )]  \
Timestamp                                                                                    
2020/10/29 4:40:30 am GMT+7                                                NaN               
2020/10/29 4:40:51 am GMT+7                                                NaN               

                            ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Original ( breast )]  \
Timestamp                                                                                     
2020/10/29 4:40:30 am GMT+7                                             ชอบมาก                
2020/10/29 4:40:51 am GMT+7                                                NaN                

                            ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Original (drumstick)]  \
Timestamp                                                                                      
2020/10/29 4:40:30 am GMT+7                                                NaN                 
2020/10/29 4:40:51 am GMT+7                                                NaN                 

                            ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Original ( back bone)]  \
Timestamp                                                                                       
2020/10/29 4:40:30 am GMT+7                                                NaN                  
2020/10/29 4:40:51 am GMT+7                                                NaN                  

                            ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Original (wing)]  \
Timestamp                                                                                 
2020/10/29 4:40:30 am GMT+7                                                NaN            
2020/10/29 4:40:51 am GMT+7                                                NaN            

                            ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Hot and Spicy ( thigh )]  \
Timestamp                                                                                         
2020/10/29 4:40:30 am GMT+7                                                NaN                    
2020/10/29 4:40:51 am GMT+7                                                NaN                    

                            ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Hot and Spicy ( breast )]  \
Timestamp                                                                                          
2020/10/29 4:40:30 am GMT+7                                                NaN                     
2020/10/29 4:40:51 am GMT+7                                                NaN                     

                            ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Hot and Spicy ( drumstick )]  \
Timestamp                                                                                             
2020/10/29 4:40:30 am GMT+7                                                NaN                        
2020/10/29 4:40:51 am GMT+7                                                NaN                        

                            ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Hot and Spicy ( back bone )]  \
Timestamp                                                                                             
2020/10/29 4:40:30 am GMT+7                                                NaN                        
2020/10/29 4:40:51 am GMT+7                                                NaN                        

                            ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Hot and Spicy ( wing )]  \
Timestamp                                                                                        
2020/10/29 4:40:30 am GMT+7                                             ชอบมาก                   
2020/10/29 4:40:51 am GMT+7                                                NaN                   

                             ... ความชอบในแต่ละเมนูของ KFC [Mashed Potatoes]  \
Timestamp                    ...  

In [131]:
df.columns

Index(['ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Original ( thigh )]',
       'ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Original ( breast )]',
       'ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Original (drumstick)]',
       'ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Original ( back bone)]',
       'ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Original (wing)]',
       'ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Hot and Spicy ( thigh )]',
       'ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Hot and Spicy ( breast )]',
       'ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Hot and Spicy ( drumstick )]',
       'ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Hot and Spicy ( back bone )]',
       'ความชอบในแต่ละเมนูของ KFC [Fried Chicken - Hot and Spicy ( wing )]',
       'ความชอบในแต่ละเมนูของ KFC [Singer Burger]',
       'ความชอบในแต่ละเมนูของ KFC [Crispy Fish Burger]',
       'ความชอบในแต่ละเมนูของ KFC [Yum Kai Zaab Rice]',
       'ความชอบในแต่ละเมนูของ KFC [Yum Kai Seed Rice]',
       'ความช

# data Clearing and Collecting

In [132]:
# Clearing the columns name
df.columns = df.columns.str.replace('ความชอบในแต่ละเมนูของ KFC ',r'')
df.columns = df.columns.str.replace('Fried Chicken - ',r'')
df.columns = df.columns.str.replace('[',r'')
df.columns = df.columns.str.replace(']',r'')
df.columns = df.columns.str.replace('(','-')
df.columns = df.columns.str.replace(')',r'')
#df.columns = df.columns[:11].union(df.columns[11:].str.lower())
df.columns

Index(['Original - thigh ', 'Original - breast ', 'Original -drumstick',
       'Original - back bone', 'Original -wing', 'Hot and Spicy - thigh ',
       'Hot and Spicy - breast ', 'Hot and Spicy - drumstick ',
       'Hot and Spicy - back bone ', 'Hot and Spicy - wing ', 'Singer Burger',
       'Crispy Fish Burger', 'Yum Kai Zaab Rice', 'Yum Kai Seed Rice',
       'Wing Zaab', 'Chicken Popcorn', 'Fish Finger', 'Nuggets',
       'French Fries', 'Mashed Potatoes', 'Tuna Corn Salad', 'Iced Coffee',
       'Floated Iced Coffee', 'Soft cream', 'Dipped Soft cream', 'Egg Tart',
       'Chilly sauce', 'Ketchups', 'Barbecue sauce'],
      dtype='object')

In [133]:
#collect score for each menu
#count[menu(0,28)][satisfaction level (0,3)]
#count_score[menu(0,28)]

count = np.zeros((29,4))
count_score = [None]*29

for i in range(len(df.columns)):
    
    count_vector=df[df.columns[i]].value_counts()
    
    if 'ไม่ชอบ' in count_vector : count[i][0] = count_vector.ไม่ชอบ
    if 'เฉยๆ' in count_vector : count[i][1] = count_vector.เฉยๆ
    if 'ชอบ' in count_vector : count[i][2]= count_vector.ชอบ
    if 'ชอบมาก' in count_vector : count[i][3] = count_vector.ชอบมาก
    print('for i = ' + str(i) + ' : ' + str(df.columns[i]) )
    print(count[i][0],count[i][1],count[i][2],count[i][3])

    count_score[i] = [sum([(count[i][x])*(x+1) for x in range(0,4)])]
    print('count_score = ' + str(count_score[i]))
    print()

for i = 0 : Original - thigh 
6.0 9.0 11.0 2.0
count_score = [65.0]

for i = 1 : Original - breast 
4.0 14.0 6.0 5.0
count_score = [70.0]

for i = 2 : Original -drumstick
3.0 12.0 10.0 4.0
count_score = [73.0]

for i = 3 : Original - back bone
8.0 12.0 4.0 4.0
count_score = [60.0]

for i = 4 : Original -wing
5.0 9.0 8.0 5.0
count_score = [67.0]

for i = 5 : Hot and Spicy - thigh 
3.0 6.0 8.0 10.0
count_score = [79.0]

for i = 6 : Hot and Spicy - breast 
4.0 8.0 9.0 6.0
count_score = [71.0]

for i = 7 : Hot and Spicy - drumstick 
3.0 5.0 9.0 10.0
count_score = [80.0]

for i = 8 : Hot and Spicy - back bone 
6.0 9.0 7.0 5.0
count_score = [65.0]

for i = 9 : Hot and Spicy - wing 
2.0 7.0 8.0 11.0
count_score = [84.0]

for i = 10 : Singer Burger
4.0 11.0 8.0 6.0
count_score = [74.0]

for i = 11 : Crispy Fish Burger
4.0 17.0 2.0 5.0
count_score = [64.0]

for i = 12 : Yum Kai Zaab Rice
3.0 11.0 11.0 3.0
count_score = [70.0]

for i = 13 : Yum Kai Seed Rice
6.0 11.0 5.0 6.0
count_score = [67.0]

In [134]:
print(count)
print(count_score)

[[ 6.  9. 11.  2.]
 [ 4. 14.  6.  5.]
 [ 3. 12. 10.  4.]
 [ 8. 12.  4.  4.]
 [ 5.  9.  8.  5.]
 [ 3.  6.  8. 10.]
 [ 4.  8.  9.  6.]
 [ 3.  5.  9. 10.]
 [ 6.  9.  7.  5.]
 [ 2.  7.  8. 11.]
 [ 4. 11.  8.  6.]
 [ 4. 17.  2.  5.]
 [ 3. 11. 11.  3.]
 [ 6. 11.  5.  6.]
 [ 3.  3.  4. 17.]
 [ 1.  6. 10. 10.]
 [ 1. 14.  6.  6.]
 [ 3.  9.  9.  6.]
 [ 3. 11.  8.  5.]
 [ 5.  8.  8.  7.]
 [ 4. 10.  8.  5.]
 [ 5. 17.  2.  3.]
 [ 6. 12.  6.  3.]
 [ 3.  8.  9.  6.]
 [ 2.  9.  9.  7.]
 [ 2.  6.  8. 11.]
 [ 5.  7.  9.  6.]
 [ 1.  9.  7. 10.]
 [ 5.  9.  6.  7.]]
[[65.0], [70.0], [73.0], [60.0], [67.0], [79.0], [71.0], [80.0], [65.0], [84.0], [74.0], [64.0], [70.0], [67.0], [89.0], [83.0], [71.0], [72.0], [69.0], [73.0], [68.0], [57.0], [60.0], [70.0], [75.0], [82.0], [70.0], [80.0], [69.0]]


# Create df2 for micro nutrition

In [ ]:
df2=pd.read_csv('KFC-micro.csv')
df2.shape

(32, 7)

In [ ]:
df2.columns = df2.columns.str.replace('Unnamed: 0','menu')
df2.head(3)

menu  Calories(g)  Fat(g)  Carb(g)  \
0    Fried Chicken - Original ( thigh )          280    19.0      6.0   
1   Fried Chicken - Original ( breast )          330    17.0     11.0   
2  Fried Chicken - Original (drumstick)          160    10.0      4.0   

   Protein(g)  Sodium (mg)  Cholesterols ( mg )  
0        21.0          410                  130  
1        33.0          640                  160  
2        14.0          240                   95

# Create df3 for df2+score+grouping

In [ ]:
group = [['main']]*14+[['side']]*7+[['dessert']]*8+[['side']]
group

[['main'],
 ['main'],
 ['main'],
 ['main'],
 ['main'],
 ['main'],
 ['main'],
 ['main'],
 ['main'],
 ['main'],
 ['main'],
 ['main'],
 ['main'],
 ['main'],
 ['side'],
 ['side'],
 ['side'],
 ['side'],
 ['side'],
 ['side'],
 ['side'],
 ['dessert'],
 ['dessert'],
 ['dessert'],
 ['dessert'],
 ['dessert'],
 ['dessert'],
 ['dessert'],
 ['dessert'],
 ['side']]

In [ ]:
#change count_score to df33 , group to df32
df33 = pd.DataFrame(count_score ,columns=['score'])
df32 = pd.DataFrame(group , columns=['Type'] )
#joining df2,df33,df32
df3=pd.concat([df2,df33],axis=1,sort=True)
df3=pd.concat([df3,df32],axis=1,sort=True)
df3

menu  Calories(g)  Fat(g)  Carb(g)  \
0            Fried Chicken - Original ( thigh )          280    19.0      6.0   
1           Fried Chicken - Original ( breast )          330    17.0     11.0   
2          Fried Chicken - Original (drumstick)          160    10.0      4.0   
3         Fried Chicken - Original ( back bone)          400    25.0     12.0   
4               Fried Chicken - Original (wing)          230    15.0      6.0   
5       Fried Chicken - Hot and Spicy ( thigh )          320    22.0     10.0   
6      Fried Chicken - Hot and Spicy ( breast )          340    18.0     18.0   
7   Fried Chicken - Hot and Spicy ( drumstick )          170    10.0      6.0   
8   Fried Chicken - Hot and Spicy ( back bone )          430    27.0     18.0   
9        Fried Chicken - Hot and Spicy ( wing )          230    15.0      9.0   
10                                Singer Burger          530    27.0     46.0   
11                           Crispy Fish Burger          470    22.0     54.0   
12                            Yum Kai Zaab Rice          640    18.0     94.0   
13                            Yum Kai Seed Rice          480     5.0     85.0   
14                                    Wing Zaab          100     6.0      5.0   
15                              Chicken Popcorn          300    16.0     23.0   
16                      Fish Finger ( 3pieces )          180     9.0     16.0   
17                                      Nuggets           45     2.5      3.0   
18                     French Fries ( regular )          150     6.0     21.0   
19                  Mashed Potatoes ( regular )           50     0.0     11.0   
20                  Tuna Corn Salad ( regular )          170    10.0     12.0   
21                         Iced Coffee ( 16oz )          200     0.0     42.0   
22                 Floated Iced Coffee ( 12oz )          240     0.0     47.0   
23                                   Soft cream          130     2.5     25.0   
24                            Dipped Soft cream          280    14.0     35.0   
25                                     Egg Tart          170    10.0     31.0   
26                                 Chilly sauce           10     0.0      3.0   
27                                     Ketchups           10     0.0      3.0   
28                               Barbecue sauce           40     0.0     10.0   
29                                     Boil egg           70     5.0      1.0   
30                                  Rice (100g)          130     0.2     28.6   
31                              Coleslaw salad           170    12.0     14.0   

    Protein(g)  Sodium (mg)  Cholesterols ( mg )  score     Type  
0         21.0          410                  130   65.0     main  
1         33.0          640                  160   70.0     main  
2         14.0          240                   95   73.0     main  
3         32.0          830                  140   60.0     main  
4         18.0          360                  120   67.0     main  
5         19.0          500                   85   79.0     main  
6         26.0          530                   80   71.0     main  
7         13.0          330                   60   80.0     main  
8         28.0          680                  100   65.0     main  
9         15.0           20                   60   84.0     main  
10        25.0         1270                   90   74.0     main  
11        15.0          980                   35   64.0     main  
12        25.0         1650                   60   70.0     main  
13        24.0         1670                   75   67.0     main  
14         7.0          210                   30   89.0     side  
15        15.0          650                   50   83.0     side  
16         8.0          380                   15   71.0     side  
17         3.0          125                   10   72.0     side  
18         2.0          150                    0   69.0     side  
19         1.0          410  

# Add on T1,T2,T3,T4,T5,T6

In [ ]:
t = [None]*6

#calulate t value
#input w h a i
while True :
    default = input('defalut value (y/n) = ')
    if default.lower() =='y' :
        w = 60
        h = 170
        a = 21
        i = 2
        sex = 'male'
        break
    elif default.lower() =='n' :
        w = input('weight(kg) = ')
        h = input('height(cm) = ')
        a = input('age = ')
        i = input('active level [1:4] = ') #i=1,2,3,4
        sex = input('sex {male,female} = ')
        break
    elif default.lower() =='view' :
        w = 80
        h = 180
        a = 21
        i = 4
        sex = 'male'
        break
    else :
        print('try to input correct alphabet : ')

level = [1.20,1.45,1.70,1.95]
bmr = 10*int(w) + 6.25*int(h) - 5*int(a) + 5
if sex.lower()=='male':
    nsex = 200
elif sex.lower()=='female':
    nsex = 0
t[0] = nsex+bmr*level[int(i)-1] #calories
#t[1] = t[0]*0.3/9 #fat(g)
#t[2] = t[0]*(0.4+(int(i)*0.05))/4 #carb(g)
#t[3] = (t[0]-((t[1]*9)+(t[2]*4)))/4 #protein(g)
t[1] = t[0]*0.4/9 #fat(g)
t[2] = t[0]*0.4/4 #carb(g)
t[3] = t[0]*0.2/4 #protein(g)
t[4] = 2000 #sodium
t[5] = 1000 #cholesterol
print('total calories = ' + str(t[0]))
print('protein = ' + str(t[3]) + ' , fat = ' + str(t[1]) + ' , carb = ' + str(t[2]))
print('sodium = ' + str(t[4]) + ' , cholesterol = ' + str(t[5]))

defalut value (y/n) = N
weight(kg) = 48
height(cm) = 158


In [ ]:
#df target
dftarget = pd.DataFrame(t).T
dftarget = dftarget.rename(index={dftarget.index[0]:'target'})
for x in range(len(dftarget.columns)):
    dftarget = dftarget.rename(columns={dftarget.columns[x]:df3.columns[x+1]})
dftarget

# Prototype

In [ ]:
prop = (df3.score[:-3])/sum(df3.score[:-3])
print(sum(prop))

menu = df3.menu[:-3].array
from numpy.random import choice
test3 = choice(menu, p = prop)
print(test3)

In [ ]:
dfnewmenu = df3.loc[df3['menu']==test3]
dfnewmenu

In [ ]:
def findnewmenu():
    global test3
    global menu
    global dfnewmenu
    test3 = choice(menu,p=prop)
    dfnewmenu = df3.loc[df3['menu']==test3]


In [ ]:
findnewmenu()
dfnewmenu

In [ ]:
#df total consume
totalcon = 0
for x in range(len(dfnewmenu.index)) :
    totalcon += (dfnewmenu.iloc[x,1:7])
dfcon = pd.DataFrame(totalcon).T
dfcon = dfcon.rename(index={dfcon.index[0]:'total consume'})
dfcon

In [ ]:
#df total different
diff= dftarget.iloc[0,:]-dfcon.iloc[0,:]
dfdiff = pd.DataFrame(diff).T
dfdiff = dfdiff.rename(index={dfdiff.index[0]:'different'})
dfdiff

In [ ]:
error = pd.DataFrame((dfdiff.iloc[0,:])*100/(dftarget.iloc[0,:])).T
error = error.rename(index={error.index[0]:'error(percent)'})
error

In [ ]:
dfsum=pd.concat([dftarget,dfcon,dfdiff,error],axis=0,sort=False)
dfsum

# selection

In [ ]:
limit = 10
limitin = 20
i = 0
k = 0
sample = 200
temp = pd.DataFrame()
stack = pd.DataFrame()
stest = pd.DataFrame()
sdfcon = pd.DataFrame()
sdfdiff = pd.DataFrame()
result = pd.DataFrame()
serror = pd.DataFrame()

In [ ]:
dfnewmenu

In [ ]:
def start() :
    global temp
    global stack
    global stest
    global sdfcon
    global sdfdiff
    global result
    global i
    temp = 0
    stack = pd.DataFrame()
    stest = pd.DataFrame()
    sdfcon = pd.DataFrame()
    sdfdiff = pd.DataFrame()
    result = pd.DataFrame()
    i = 0
    newmenu()
    

#menu
def newmenu() :
    
    global dfnewmenu
    global prop
    global stest
    global stack
    global sdfcon
    
    if i > sample-sample*0.2 :
        stest = df3.filter(items=[random.randint(29, 31)],axis=0)
        print('i>sample-10')
    else :
        findnewmenu()
        stest = dfnewmenu #need better random with weighting factor
    
    stesti = pd.DataFrame(stest.iloc[0,1:7]).T
    stack = pd.concat([stack,stesti])
    stack = stack.rename(index={stack.index[-1]:stest.iloc[0,0]})
    print()
    print('new stack having : '+str(len(stack.index)))
    #sdfcon or total consumtion
    stotalcon = 0
    for x in range(len(stack.index)) :
        stotalcon += (stack.iloc[x,:])
    sdfcon = pd.DataFrame(stotalcon).T
    sdfcon = sdfcon.rename(index={sdfcon.index[0]:'total consume'})
    diff()
    
    
def eliminate() :
    global stack
    global i
    stack = stack.head(len(stack.index)-1)
    i += 1
    print('stack -1')
    print('i = '+str(i))
    


def diff() : #just find diff not checking
    global sdfcon
    global dftarget
    global sdfdiff
    global serror
    global errormean
    global i
    global sample
    #sdiff
    sdiff = dftarget.iloc[0,:]-sdfcon.iloc[0,:]
    sdfdiff = pd.DataFrame(sdiff).T
    sdfdiff = sdfdiff.rename(index={sdfdiff.index[0]:'different'})
    #serror
    serror = sdfdiff*100/(dftarget.iloc[0,:])
    serror = serror.rename(index={serror.index[0]:'error'})
    #mean
    errormean = sum(abs(serror.iloc[0,serror.columns != 'Sodium (mg)']))/((len(serror.columns[:]))-1) #might be[:-2]
    #get new error mean but still not confirm.
    
    if temp == 0 :
        print('temp = 0')
        checkerror()
    else :
        print('having temp')
        if i<sample :
            print('go to checkmean2temp')
            checkmean2temp()
            print('done check2temp')
        else :
            print('enough , i is maximum.')
            output()
            print()
            print('w a r n i n g - w a r n i n g - w a r n i n g')
            print()
        

# id error > limit
def checkerror():
    global serror
    global limitin
    global temp
    global errormean
    print('new menu = ' + str(stest.iloc[0,0]))
    for x in range(len(serror.columns)) :
        print('x = ' + str(x))
        if serror.iloc[0,x]>limitin : #macro is lack then newmenu
            print(str(serror.columns[x])+' is outside limitin : error(%) = '+str(serror.iloc[0,x]))
            temp = errormean
            print('temp saved')
            print('break to new menu')
            newmenu()
            print('break from check error')
            break
        elif abs(serror.iloc[0,x])>20 : #macro is surplus then stack-1 , newmenu
            print(str(serror.columns[x])+' is outside limitin : error(%) = '+str(serror.iloc[0,x]))
            print('go to eliminate')
            eliminate()
            print('eliminated then... newmenu')
            newmenu()
            print('break from checkerror')
            break
        else :
            print(str(serror.columns[x])+' is inside limitin : error(%) = '+str(serror.iloc[0,x]))
            if x == 5 :
                checkmean()
                print('nice job , every macro is in limitin. Then checkmean')

                
def checkmean() :
    global errormean
    global limit
    global temp
    print('error mean = '+ str(errormean))
    if errormean < limit :
        print( 'error mean is less than limit , lets do output' )
        output()
    else :
        print('error mean is too large , fine , save error in temp')
        temp = errormean
        print('temp saved')
        newmenu()          
        
#check if this new stack has less diff
def checkmean2temp () :
    global temp
    global i
    global errormean
    global k
    if abs(errormean)<abs(temp) :
        print('new errormean < temp(oldmean) : '+str(errormean)) 
        #confirm errormean is better
        print('go to check error')
        checkerror()
        print('done checkerror')
    else :
        print('This errormean > temp(olderror) , eliminate it and newmenu')
        k += 1
        if k == 3 :
            print('double eliminate')
            eliminate()
        eliminate()
        print('done eliminate')
        print('go newmenu')
        newmenu()
        print('done newmenu')

def output():
    global stack
    global sdfcon
    global serror
    global sdfdiff
    global dftarget
    global result
    global errormean
    result = pd.concat([dftarget,sdfcon,sdfdiff,serror,stack])
    print('Average error is '+str(errormean))

# start here

In [ ]:
start()

# result

In [ ]:
result

In [ ]:
errormean

In [ ]:
dftarget

In [ ]:
sdfcon

In [ ]:
sdfdiff

In [ ]:
serror

In [ ]:
stack

In [ ]:
df3.iloc[3,:]

In [ ]:
stesti = pd.DataFrame(stest.iloc[0,1:7]).T
stesti

In [ ]:
#df3.filter(items=[20],axis=0)
#df3.filter(items=[20],axis=0)
#df3.filter(items=[29],axis=0)
random.randint(29, 31)

In [ ]:
findnewmenu()

In [ ]:
df3.columns

In [ ]:
df3.iloc[:,1] > 200

In [ ]:
def caloriesmorethan(k) :
    global df3
    
    for i in range(len(df3.iloc[:,:])):
        if df3.iloc[i,1] > k :
            print(df3.menu[i])
            print('Calories = '+str(df3.iloc[i,1]))
            #print(df3.)
            #row = 
    return

In [ ]:
max(df3.iloc[:,1])

In [ ]:
caloriesmorethan(500)